apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: consumerapi-service
  namespace: consumer-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: consumerapi
status:
  loadBalancer: {}
